import { Inter } from "next/font/google";
import "./globals.css";
import SIdebar from "./_components/SideBar/SIdebar";
import ClientProvider from "./_components/ClientProvider/ClientProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
     
      
      <body className={inter.className}>

  <ClientProvider>
      <div className="flex h-screen bg-gradient-to-r from-[#F5BCBA] to-[#C3C7FE] p-4">
      <div className="flex gap-x-4 rounded-3xl overflow-hidden w-full">
        <SIdebar />
        <main className="flex-1 p-6 bg-green-300 rounded-r-3xl border overflow-auto bg-gradient-to-r from-[#F5BCBA] to-[#C3C7FE] transition duration-300  ">
         
          {children} 

         
        
        </main>
      </div>
    </div>
    </ClientProvider>
        </body>
    </html>
  );
}
