import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProviders from "@/Providers/next-auth-providers";
import GlobalState from "@/Context";
import Header from "./_components/Header/Header";
import Footer from "./_components/Footer/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark:bg-black" >
       
          <NextAuthProviders>
            <GlobalState>
             <div>
             <Header />
              </div> 
              {children}
<div>
  <Footer />
</div>
            </GlobalState>
          </NextAuthProviders>
          
      </body>
    </html>
  );
}
