import UpArrowButton from "./_components/ArrowButton/ArrowButton";
import Footer from "./_components/Footer/Footer";
import Header from "./_components/Header/Header";
import Head from "next/head";
import "./globals.css";

export const metadata = {
  title: "GlitchyDevs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <link rel="icon" href="/logo.png" />
      </Head>
      <body>
        <div>
          <Header />
        </div>
        {children}
        <div>
          <Footer />
        </div>
        {/* Include the UpArrowButton component */}
        <UpArrowButton />
      </body>
    </html>
  );
}
