import { Lora } from 'next/font/google';
import "./globals.css";
import SideBar from "./_componenents/Dialog/Dialog";
import Header from "./_componenents/Header/Header";
import Footer from "./_componenents/Footer/Footer";

const lora = Lora({ subsets: ['latin'] });

export const metadata = {
  title: "GlitcherHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
<body className={lora.className}>
  <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
